version: "3.9"

services:
  delivery:
    image: postgres
    container_name: delivery
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=delivery
    volumes:
      - pgdata:/data/postgres
  # app:
  #   build: .
  #   container_name: rentalx
  #   restart: always
  #   ports:
  #     - 3333:3333
  #     - 9229:9229
  #   volumes:
  #     - .:/usr/app
  #     - /usr/app/node_modules
  #   links:
  #     - delivery
  #   depends_on: 
  #     - delivery

volumes:
  pgdata:
    driver: local